apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: poc-configuration-management-{{ .Values.pr }}
  namespace: flux-system
spec:
  path: ./clusters/develop-azure/poc-configuration-management/previews
  interval: 1m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: fleet-online.devtick
  prune: true
  validation: client
  decryption:
    provider: sops
  postBuild:
    substitute:
      namespace: {{ .Values.pr }}
      tag: {{ .Values.tag }}
